### ISSUE TITLE
Remove Apache Snapshot repository

### ISSUE THREAD

**Issue by retog** [fusepoolP3/p3-pipeline-gui#2]
We should not depend on anything that isn't in maven central.

**Comment by gaborremenyi** [comment]
You mean this right?
    <repositories>
        <repository>
            <releases>
                <enabled>false</enabled>
            </releases>
            <id>apache.snapshots</id>
            <name>Apache Snapshot Repository</name>
            <url>http://repository.apache.org/snapshots</url>
        </repository>
    </repositories>

This does not only affect the pipeline GUI, there are some other repos that have the same snippet in their pom.xml.

**Comment by gaborremenyi** [comment]
Sorry I forgot the to mark it as code...
`    <repositories>`
`        <repository>`
`            <releases>`
`                <enabled>false</enabled>`
`            </releases>`
`            <id>apache.snapshots</id>`
`            <name>Apache Snapshot Repository</name>`
`            <url>http://repository.apache.org/snapshots</url>`
`        </repository>`
`    </repositories>`

**Comment by retog** [comment]
Yes, I mean this one. Please rise issues or remove this from other projects as well.

In general:

- Never use SNAPSHOT dependencies unless there is no released version providing the required functionality
- For every SNAPSHOT dependency create a github issue (A) in the project as well as one (B) in the project of the dependency. The issue (A) should mention why the SNAPSHOT version is needed and link to (B). Issue (B) should ask for the project to be released.
- For Fusepool P3 projects the github issues asking for a release should be assigned to me.
