### ISSUE TITLE
Release for sandbox

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-pipeline-gui#7]
Gabor did a new release which should hopefully fix the issue on sandbox, @retog could you make sure that there is a new release pulled?

**Comment by retog** [comment]
The last build of the refernce implementation docker was 7 days ago, and the last release of pipeline-gui dated August 19th. What release are you referring to?

**Comment by gaborremenyi** [comment]
He is referring to this release: https://github.com/fusepoolP3/p3-pipeline-gui/releases/tag/v1.0.0-20151022
The current version running on sandbox (http://sandbox.fusepool.info:8201) is not the latest release, I checked the js code in a browser.

**Comment by retog** [comment]
What's weird is that I read

 v1.0.0-20151022
@gaborremenyi gaborremenyi released this on 19 Aug 

On https://github.com/fusepoolP3/p3-pipeline-gui/releases

Next time you do a release don't forget to trigger the rebuild of the docker.
