### ISSUE TITLE
Registered transformer UI is not correct

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-pipeline-gui#8]
The dashboard does not get the correct URI of a registered pipeline, all it sees is the base URI of the pipeline transformer. In the test-dialog of the pipeline UI the full URI is present and if I manually register a widget with this transformer URI it is fine.

**Comment by gaborremenyi** [comment]
Fix with latest commit.

**Comment by ktk** [comment]
I just tried the latest version on Sandbox (timestamp `2015-12-30T08:33:20.242Z`) as UI for playground by specifying a different [platform URI](http://sandbox.fusepool.info:8201/test.html?platformURI=http://playground.fusepool.info/&transformerBase=http://playground.fusepool.info:8300/#). I created a new transformer, when I store it the URI it generates in the test is:

    http://playground.fusepool.info:8300/?config=http%3A%2F%2Fplayground.fusepool.info%3A8181%2Fldp%2Ftr%2FL

No matter what I try this URI does not work. When I manually look it up in the LDP UI and execute it against

    http://playground.fusepool.info:8300/?config=http://playground.fusepool.info:8181/ldp/tr/L

It works

**Comment by ktk** [comment]
@gaborremenyi any updates to this? The issue is still not fixed and we have final review meeting in a few weeks.

**Comment by gaborremenyi** [comment]
Sorry for the late response. However I think that the URI generated by the UI is correct. There was a problem a month ago where the pipeline transformer could not decode URL encoded config URIs. So my guess would be that playground is not using the latest the  version of pipeline transformer, which would be this: https://github.com/fusepoolP3/p3-pipeline-transformer/releases/tag/v1.0.0-20151216

Can you update it on playground? Or should I ask Reto? I'll leave the issue open until then.

**Comment by ktk** [comment]
I didn't mention that but it doesn't seem to make a difference if I do it on sandbox, which is from this year.

**Comment by gaborremenyi** [comment]
But it does make a difference, because the error messages are not the same.

On playground you get a MalformedURLException which was fixed in the latest pipeline. On sandbox the pipeline transformer simply just cannot establish a connection to http://playg
round.fusepool.info:8305/... which is the first transformer in the pipeline.

I still don't see any problem with the pipeline URI created by the UI.

```
$ curl -X GET "http://playground.fusepool.info:8300/?config=http%3A%2F%2Fplaygr
ound.fusepool.info%3A8181%2Fldp%2Ftr%2FL"
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /. Reason:
<pre>    java.lang.RuntimeException: java.net.MalformedURLException: no protocol
: http%3A%2F%2Fplayground.fusepool.info%3A8181%2Fldp%2Ftr%2FL</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```
```
$ curl -X GET "http://sandbox.fusepool.info:8300/?config=http%3A%2F%2Fplaygroun
d.fusepool.info%3A8181%2Fldp%2Ftr%2FL"
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /. Reason:
<pre>    java.lang.RuntimeException: Cannot establish connection to http://playg
round.fusepool.info:8305/?transformer=http%3A%2F%2Fplayground.fusepool.info%3A83
04%2Ftransformers%2Fchain%2Falod-linking&amp;lit-pred=http%3A%2F%2Fpurl.org%2Fdc
%2Felements%2F1.1%2Ftitle&amp;lit-pred=http%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1
.1%2Fdescription&amp;lit-pred=http%3A%2F%2Fdata.archiveshub.ac.uk%2Fdef%2Fnote !
</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

**Comment by ktk** [comment]
So I re-setup data.fusepool.info with latest versions of everything and indeed in here it seems to work! I close this as it looks fine so far, thanks!

**Comment by retog** [comment]
I'm confused, does it work on sandbox?

**Comment by ktk** [comment]
I need to try it on sandbox, never did a full pipeline there. What I did was using the sandbox UI with playground platform and that didn't work. I assume this was because playground was running an old version of the platform.

**Comment by gaborremenyi** [comment]
I'm glad it's working now, let me know if you have any other issues with the UI.
